- name: main
  gather_facts: no
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  vars:
    ansible_become_timeout: 30
  vars_files:
  - ./variable/valiable.yml
  tasks:
  - include: ./config/user.yml
  - include: ./config/packges.yml
  - include: ./config/nginx.yml
  - include: ./config/rvm.yml
  - include: ./config/mysql5.7.yml
  - include: ./config/redis.yml
  - include: ./config/node14.yml

