- name: main
  gather_facts: no
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  vars:
    ansible_become_timeout: 30
  vars_files:
  - ./valiable.yml
  tasks:
  - include: ./user.yml
  - include: ./packges.yml
  - include: ./nginx.yml
  - include: ./rvm.yml
  - include: ./mysql5.7.yml
  - include: ./redis.yml
  - include: ./node14.yml

