   - name: add keys
     ansible.builtin.apt_repository:
      repo: "{{ item }}"
     loop:
        - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
        - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
        - "deb http://security.ubuntu.com/ubuntu/ bionic-security main" 
     ignore_errors: true
   - name: add keys
     apt_key:
      keyserver: keyserver.ubuntu.com
      id: 40976EAF437D05B5
   - name: Fix problems with packages
     shell: sudo dpkg --configure -a
   - name: upgrade
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   - name: install packages using shell
     shell: "sudo apt install curl g++ gcc autoconf automake bison libc6-dev libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev make pkg-config sqlite3 zlib1g-dev libgmp-dev libreadline-dev libssl-dev libjpeg-dev libpng-dev libtiff-dev libwebp-dev  zlib1g zlib1g-dev libmysqlclient-dev -y" 