- name: install redis
  apt:
    name: redis-server
    update_cache: yes
    state: latest
- name: 'Start the Redis service'
  become: true
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: yes
    use: service
