- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: ppa:rael-gc/rvm
    state: present
    update_cache: true
- name: rvm install
  shell: "/bin/bash -c -l  'curl -sSL https://get.rvm.io | bash'"
  register: rvm_output
# - name: print rvm installation output
# debug: var = rvm_output  
- name: install ruby "{{ ruby_version}}"
  shell: /bin/bash -l -c "rvm install "{{ ruby_version }}""
